[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/checkout.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      X-Frame-Options = "SAMEORIGIN"
      X-Content-Type-Options = "nosniff"
